name: Dependabot auto-merge (patch/minor)

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve patch/minor updates
        if: |
          ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
              steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge (squash)
        if: |
          ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
              steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
